services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: taskly-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskly
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Backend/src/migrations:/migrations
    networks:
      - taskly-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: taskly-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/taskly
      PORT: 4000
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taskly-network
    ports:
      - "4000:4000"
    command: >
      /bin/sh -c "node src/migrate.js && node src/server.js"
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: taskly-frontend
    depends_on:
      - backend
    networks:
      - taskly-network
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  taskly-network:
    driver: bridge
