[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = [
  "cd Backend && npm ci --omit=dev",
  "cd ../Frontend && npm ci"
]

[phases.build]
cmds = ["cd Frontend && npm run build"]

[start]
cmd = "cd Backend && npm start"